# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04e6f1743b6ee8410507c0768d8282a6"
name = "BrandFlow"
application_url = "https://oa5j5bfjk9wyp3i167muzk0j.91.239.208.85.sslip.io"
embedded = true
handle = "brandflow"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://oa5j5bfjk9wyp3i167muzk0j.91.239.208.85.sslip.io/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://oa5j5bfjk9wyp3i167muzk0j.91.239.208.85.sslip.io/api/auth/callback" ]
